### ISSUE TITLE
Version compability/using as dependency

### ISSUE THREAD

**Issue by MituuZ** [redhat-developer/lsp4ij#207]
Hey,

just stumbled upon this repo and it sounds awesome and just what I was looking for. Having some issues with adding the plugin as a dependency, as I wanted to take for a ride. (generated the initial project with 241 if that matters)

I'm assuming here that when defining a plugin dependency to plugin.xml it fetches the package from the marketplace.

From the [marketplace](https://plugins.jetbrains.com/plugin/23257-lsp4ij/versions) it seems that the supported version is 223+ (while plugin.xml defines since 231 in main) , but when trying with 241, 233 or 223 versions of IntelliJ Idea each of them throw the same message:

![image](https://github.com/redhat-developer/lsp4ij/assets/55958056/df4deef9-4e6d-4d6f-b0ba-b4dfc882f159)

So adding the dependency to plugin.xml like on this any of the three versions and trying to build always fails with the package `com.redhat.devtools.lsp4ij` not existing.
```
<depends>com.redhat.devtools.lsp4ij</depends>
```

Not sure is this should be an issue or if it should have been send to discussions instead.

**Comment by angelozerr** [comment]
@MituuZ I'm very glad that LSP4IJ could interest you.

At first there are no release for the moment and we have the intention to do that soon once I will finish my worj with rename support. Perhaps your problem comes from that they are no release?

I don't master IntelliJ version mechanism, so I will see this problem with @fbricon .

We use LSP4IJ in https://github.com/redhat-developer/intellij-quarkus so perhaps you could see discover the problem by seeing this  project?

If you want to test your LS with LSP4IJ quickly, you can do that without developping an Intellij Plugin, see https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserDefinedLanguageServer.md just to check that LSP4IJ will provide enough features that you need with good performance .

You will needjust to install the nightly builds https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds

If you do that please take care of https://github.com/redhat-developer/lsp4ij/issues/206

Which LS do you want to integrate?

**Comment by MituuZ** [comment]
Thanks for the quick response. 

Didn't notice that the versions in the marketplace are under nightly, so that is probably the issue. 
I'll try to verify and see how the Quarkus repository handles this.

I'm looking to implement a small Cobol LS, have been looking some files at work and thought that it might be fun to add some functionality for them. I'm also looking forward to getting more familiar with this project too.

**Comment by angelozerr** [comment]
>I'm looking to implement a small Cobol LS, have been looking some files at work and thought that it might be fun to add some functionality for them. I'm also looking forward to getting more familiar with this project too.

Nice! The only requirement is that your Cobol LS should support stdio, but I suggest before writing an IJ plugin that you try it with https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserDefinedLanguageServer.md

**Comment by MituuZ** [comment]
I'll start with that 👍 Thank you!

**Comment by fbricon** [comment]
In order to build a plugin against nightly LSP4IJ, one needs to do something like: 
https://github.com/redhat-developer/intellij-quarkus/blob/main/build.gradle.kts#L149-L158

Basically, it'll build against a locally built LSP4IJ, living in the same parent directory as the current plugin, or will fetch the [latest nightly build](https://github.com/redhat-developer/intellij-quarkus/blob/main/build.gradle.kts#L306-L324).

The minimum supported Jetbrains platform is 231. Later versions should work, if not, then it's a bug. Earlier versions should not. I'll take a look at what's advertised on the marketplace (223 is wrong/out-of-date)

**Comment by angelozerr** [comment]
@MituuZ since you have created a PR at https://github.com/redhat-developer/lsp4ij/pull/209 (thanks so much for that!) I wonder if your Cobol LS is working?

If yes, what is your first feeling about features and performances? Don't hesitate to create any issues to improve LSP4IJ.

Thanks so much for your contribution, it will give me some time again to implement other LSP features like https://github.com/redhat-developer/lsp4ij/issues/23 that I have started.

**Comment by MituuZ** [comment]
Unfortunately I did not get it working yet, got side tracked with the balloon :smile:

I'll try to keep notes of how my implementation goes and what issues I run into.

**Comment by angelozerr** [comment]
Can we download somewhere your LS?

**Comment by angelozerr** [comment]
Have you some stack trace error in the LSP console?

**Comment by MituuZ** [comment]
The command seems to be running ok and the retries are running correctly. I'm using a gradle task to start the LS

The issue lies with the LS itself, it is not worth sharing at this point :smile:

**Comment by angelozerr** [comment]
Do you see some stacktrace in LSP console?  Or some LSP request / response (after activate server trace to verbose)?

Can I try it (please give me a link to download the cobol ls)?
