### ISSUE TITLE
Potential ReDoS vulnerability

### ISSUE THREAD

**Issue by InSyncWithFoo** [redhat-developer/lsp4ij#301]
For example, when `a*a*a*...` (49 times) `a` is matched against `aaa...` (100 times) `.b`:

```kotlin
import java.nio.file.Path
import java.nio.file.FileSystems

fun main() {
    val path = Path.of("a".repeat(100) + ".b")
    val matcher = FileSystems.getDefault().getPathMatcher("glob:" + "a*".repeat(50).dropLast(1))
    
    println(matcher.matches(path))  // Takes an unbearable long time
}
```

I tried doing so just now. It caused an UI freeze and peaked CPU usage.

**Comment by fbricon** [comment]
What exactly are you testing? How is that pertaining to lsp4ij?

**Comment by angelozerr** [comment]
Are you speaking about LSP FileSystemWatcher which matches some glob pattern to know if  `workspace/didChangeWatchedFiles` must be sent?

If it that we have a lot of tests (same than vscode) in https://github.com/redhat-developer/lsp4ij/blob/main/src/test/java/com/redhat/devtools/lsp4ij/features/files/FileSystemWatcherManagerTest.java

and too https://github.com/redhat-developer/lsp4ij/blob/main/src/test/java/com/redhat/devtools/lsp4ij/features/files/PathPatternMatcherTest.java which expand patterns because Java IO glob cannot support syntax `*` which must be optinal. Perhaps there is a bug with this expansion?

Could you write tests which reproduce your problem please.

**Comment by angelozerr** [comment]
Ok I have said you this path pattern is used to know if workspace/didChangeWatchedFiles must be sent. 

Have you an usecase with this `a*a*a*` returned by your language server?

**Comment by angelozerr** [comment]
Thanks for your explication!

In your usecase we dont use path pattern but a class from IJ.

I think you should have the same problem if you create from IJ préférences a file type and you open the file without language server.

**Comment by angelozerr** [comment]
Yes since we use IJ code. I suggest that you report the issue to Jetbrains.
