### ISSUE TITLE
Override default behaviour for `signatureHelp`

### ISSUE THREAD

**Issue by InSyncWithFoo** [redhat-developer/lsp4ij#373]
<kbd>Ctrl</kbd> + <kbd>P</kbd> doesn't trigger the language server's `textDocument/signatureHelp`, but PyCharm's default:

![](https://github.com/redhat-developer/lsp4ij/assets/122007197/8c6f5570-ae19-4697-a343-353b5d05156f)

I already added the `<codeInsight.parameterInfo/>` element as guided by [the docs](https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPSupport.md#signature-help).

Am I missing something?

---

To reproduce, clone [this PR](https://github.com/InSyncWithFoo/pyright-for-pycharm/pull/42), run `runIde`, choose a Python interpreter (Python 3.12+), [install Pyright](https://insyncwithfoo.github.io/pyright-for-pycharm/how-to/#how-to-install-the-pyright-executables) and set up the path in <i>Settings</i>, then open a file and paste the following:

```python
from collections.abc import Callable

class Decorator[**P, T]:
	def __init__(self, f: Callable[P, T]) -> None:
		...
	def __call__(self, *args: P.args, **kwargs: P.kwargs) -> T:
		...

@Decorator
def add(x: int, y: int) -> int:
	return x + y
```

```python
add()  # < Place the cursor between the parentheses, then press Ctrl + P.
       # Notice that there are no `signatureHelp` requests sent.
```

Compare with VSCode:

![](https://github.com/redhat-developer/lsp4ij/assets/122007197/386d10de-e584-4f50-b974-0063b1e09b22)

**Comment by angelozerr** [comment]
Have you tested without installed PyCharm, is it working?

**Comment by angelozerr** [comment]
> To reproduce, clone https://github.com/InSyncWithFoo/pyright-for-pycharm/pull/42, run runIde, choose a Python interpreter (Python 3.12+)

No need to do that to try your ls. You can create a user defined ls, like :

![image](https://github.com/redhat-developer/lsp4ij/assets/1932211/0608931e-f200-4ff9-97a0-b8b8e6a93e6b)

and I can see your signature help:

![image](https://github.com/redhat-developer/lsp4ij/assets/1932211/75ddde05-c4d0-4323-a6b9-208a65e85f40)

It is working in my case because the py file has tetmate language. In your case you need to do like you did because your py file has Python language.

I suggest that you try to use `order="first"`
:

```
<codeInsight.parameterInfo
			id="PyrightLSPParameterInfoHandler"
                       order="first"
			language="Python"
			implementationClass="com.redhat.devtools.lsp4ij.features.signatureHelp.LSPParameterInfoHandler"
		/>

```

but it means that it will override signature help of PyCharm

**Comment by angelozerr** [comment]
> Adding order works for me.

Great!

> Please edit the docs to also mention this attribute.

Please create a PR for explaining that.
