### ISSUE TITLE
LSP4IJ is not recognized for 2024.3

### ISSUE THREAD

**Issue by InSyncWithFoo** [redhat-developer/lsp4ij#534]
LSP4IJ and its extension points are not recognized:

![](https://github.com/user-attachments/assets/0360314b-31f3-492e-9bed-2ad6e3fafec2)
![](https://github.com/user-attachments/assets/d85bd9cd-4d57-459f-b446-673f540d9061)

Any ideas what could go wrong? I'm targeting PyCharm Professional 2024.3 (`243-EAP-SNAPSHOT`/243.15521.16). My other plugins targeting older versions are fine.

**Comment by angelozerr** [comment]
I think it is because [0.5.0](https://plugins.jetbrains.com/plugin/23257-lsp4ij/edit/versions/stable/600505) is not compatible with 2024

![image](https://github.com/user-attachments/assets/e090adcf-8aa7-45b1-bc17-8f422babff1d)

but we have fixed the issue for 0.6.0 https://plugins.jetbrains.com/plugin/23257-lsp4ij/edit/versions/nightly/606717

![image](https://github.com/user-attachments/assets/61a34da5-6e12-48fe-90f6-63820046f852)

I feel your question "When you will release 0.6.0?", I wanted to implement some features before releasing, but we can discuss about that.

**Comment by fbricon** [comment]
@angelozerr internal API usage has nothing to do with 2024.3 compatibility

**Comment by angelozerr** [comment]
> @angelozerr internal API usage has nothing to do with 2024.3 compatibility 

You mean that my explanation is wrong? If it that have you somenidea why @InSyncWithFoo have problem with 2024.3?

**Comment by angelozerr** [comment]
@InSyncWithFoo when you use nighty build, have you this problem?

**Comment by angelozerr** [comment]
Ok so we can close this issue since 0.6.0 seems resolving your issue and it will be available next week?
