### ISSUE TITLE
Path patching API

### ISSUE THREAD

**Issue by InSyncWithFoo** [redhat-developer/lsp4ij#702]
(As requested at [this issue](https://github.com/InSyncWithFoo/pyright-for-pycharm/issues/93).)

Windows users sometimes have their projects and language servers located within a WSL distro (say, Ubuntu). The IDE itself is run on the Windows side, however, so things get really murky.

From the Windows side, the paths to the language server and the project are UNC paths:

```text
\\wsl$\Ubuntu\usr\bin\foo-language-server
\\wsl$\Ubuntu\home\insync\project
# or
\\wsl.localhost\Ubuntu\usr\bin\foo-language-server
\\wsl.localhost\home\insync\project
```

The server process, however, is provided and replies with absolute Linux paths:

```text
/home/insync/project
/home/insync/project/src/file.ext
```

Since the IDE runs on the Windows side, it wouldn't know where this path points to (such paths are considered relative on Windows).

To make matters worse, the language server process is also started from Windows, so the working directory passed to `GeneralCommandLine()` must be specified using an UNC path. If the project has a SDK whose path must also be passed to the server, that will need to be handled as well. Not to mention, in some cases the IDE just won't handle WSL paths correctly (as revealed at the aforementioned issue), leading to bad experience for both the developer and user.

----

We plugin developers need a way to convert such paths before they are sent to the language servers and before they are used by the IDE. The native client allows it, so here's [what I currently do](https://github.com/InSyncWithFoo/pyright-for-pycharm/blob/94d9b61f978dec393c19e8cc3955d007107a0b71/src/main/kotlin/com/insyncwithfoo/pyright/lsp/PyrightServerDescriptor.kt#L79-L96):

```kotlin
override fun getFileUri(file: VirtualFile): String {
    return when {
        wslDistribution == null -> super.getFileUri(file)
        else -> makeFileURI(wslDistribution!!.getWslPath(Path.of(file.path))!!)
    }
}

override fun findFileByUri(fileUri: String) =
    findFileByUri(URI.create(fileUri))

private fun findFileByUri(fileUri: URI): VirtualFile? {
    val virtualFileUri = when {
        wslDistribution == null || fileUri.pathIsAbsoluteDos -> fileUri
        else -> Path.of(wslDistribution!!.getWindowsPath(fileUri.path)).toUri()
    }
    
    return super.findFileByUri(virtualFileUri.toString())
}
```

**Comment by angelozerr** [comment]
@InSyncWithFoo I have implemented the API, See https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPApi.md

![Image](https://github.com/user-attachments/assets/fa42754f-9697-4802-b564-93186113ff53)

You can install nigthy build.

Compare to native LSP API, the LSP4IJ API uses URi instead of String for `URI getFileUri(VirtualFile file)` internally LSP4IJ works with URI (to store some cache as URI key). URI is better than String to manage key cache because for instance

 * `file://c/foo.txt`
 * `file://C/foo.txt`

Please test the API and tell me if it is working for you. As long as we do no release we can break anything.

I had to do a big refactoring, sorry if I have broken something and don't hesitate to create any issues.

Thanks.
